DEFAULT_CATEGORY_TREE = {
    "income": {
        "salary": [],
        "others": ["compensation", 
                   "gifts", 
                   "freelance", 
                   "resale",
                   "sublet", 
                   "refunds"],
        "investments": ["interest", 
                        "dividends"],
    },
    "expense": {
        "food": ["groceries", 
                 "eating out", 
                 "coffee"],
        "transport": ["car", 
                      "public transport", 
                      "rideshare", 
                      "train", 
                      "bus", 
                      "flight"],
        "entertainment": [
            "movies",
            "concerts",
            "clubs",
            "festivals",
            "activities",
            "sports",
            "alcohol",
            "cigarettes",
        ],
        "health": ["doctor visits", 
                   "medication"],
        "personal": [
            "clothing",
            "electronics",
            "home goods",
            "toiletry",
            "gifts",
            "plants",
            "books",
        ],
        "housing": [
            "rent",
            "accommodation",
            "utilities",
            "internet",
            "phone/mobile",
            "subscriptions",
            "insurance",
        ],
        "others": ["fees",
                   "donations", 
                   "taxes", 
                   "miscellaneous"],
    },
}
